app:
    resource: '@AppBundle/Controller/'
    type: annotation

quocquang:
    path: /quocquang/
    defaults: { _controller: AppBundle:QuocQuang:index }

blogcomment123_blogcomment:
    resource: "@AppBundle/Resources/config/routing/blogcomment.yml"
    prefix:   /app_blogcomment/

app_plscourse:
    resource: "@AppBundle/Resources/config/routing/plscourse.yml"
    prefix:   /plscourse123/

app_blogpost_blog : 
    resource : "@AppBundle/Resources/config/routing/blogpost.php"
    prefix : /app_blogpost/