plscourse_index:
    path:     /
    defaults: { _controller: "AppBundle:PlsCourse:index" }
    methods:  GET

plscourse_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:PlsCourse:show" }
    methods:  GET

plscourse_new:
    path:     /new
    defaults: { _controller: "AppBundle:PlsCourse:new" }
    methods:  [GET, POST]

plscourse_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:PlsCourse:edit" }
    methods:  [GET, POST]

plscourse_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:PlsCourse:delete" }
    methods:  DELETE
