app_blogcomment:
    resource: "@AppBundle/Resources/config/routing/blogcomment.yml"
    prefix:   /
app_plscourse:
        resource: "@AppBundle/Resources/config/routing/plscourse.yml"
        prefix:   /